[project]
name = "package-core"
dynamic = ["version"]

[project.scripts]
demo-package = "package_core.main:cli"

[tool.hatch.version]
path = "package_core/__init__.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
